
name: quiz-prod

services:
  fe:
    build:
      context: ..
      dockerfile: ci/docker/Dockerfile
    container_name: quiz_fe_prod
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    networks:
      - quiz_network_prod

volumes:
  postgres_data_prod:
    name: postgres_data_prod

networks:
  quiz_network_prod:
    name: quiz_network_prod
    driver: bridge
